/**
 * Deterministic-template string catalog, English + Spanish.
 * Interpolation: {name} placeholders. The LLM narrative is generated in the
 * target language separately; everything else renders from here.
 */
import type { Language } from '../schema/index.js';

const STRINGS = {
  en: {
    // Section titles
    'section.executiveSummary': 'Executive Summary',
    'section.keyNumbers': 'Key Numbers',
    'section.highlights': 'Highlights',
    'section.repoActivity': 'Repository Activity',
    'section.contributors': 'Contributors',
    'section.appendix': 'Appendix — methodology & caveats',

    // Key numbers labels
    'metric.prsOpened': 'PRs opened',
    'metric.prsMerged': 'PRs merged',
    'metric.mergedToProduction': 'Merged to production',
    'metric.mergedToStaging': 'Merged to staging',
    'metric.openPrTotal': 'PRs currently open',
    'metric.issuesOpened': 'Issues opened',
    'metric.issuesClosed': 'Issues closed',
    'metric.commits': 'Commits (work branches)',
    'metric.reviewsSubmitted': 'Reviews submitted',
    'metric.linesChanged': 'Lines changed (merged PRs)',
    'metric.medianTimeToMerge': 'Median time to merge',
    'metric.activeContributors': 'Active contributors',
    'metric.activeRepos': 'Active repos',

    // Table headers
    'table.repo': 'Repository',
    'table.person': 'Contributor',
    'table.prsOpened': 'PRs opened',
    'table.prsMerged': 'PRs merged',
    'table.openPrs': 'Open PRs',
    'table.issues': 'Issues (opened/closed)',
    'table.issuesOpened': 'Issues opened',
    'table.commits': 'Commits',
    'table.openPrsNow': 'Open now',
    'table.linesChanged': 'Δ lines',
    'table.reviews': 'Reviews',
    'table.merges': 'Merges',
    'table.longTail': '…and {count} more repos ({prsMerged} PRs merged, {commits} commits)',

    // Highlights
    'highlight.oldest-open-pr': '🕰️ **Oldest open PR**: [{repo}#{number}]({url}) “{title}” by @{author} — open for {ageDays} days.',
    'highlight.top-merger': '🚢 **Top merger**: {entries}.',
    'highlight.top-reviewer': '🔍 **Top reviewer**: {entries}.',
    'highlight.stale-prs': '🧊 **PRs awaiting first review** ({totalStale} total ≥{thresholdDays}d):',
    'highlight.stale-prs.item': '[{repo}#{number}]({url}) “{title}” by @{author} — {ageDays} days',
    'highlight.biggest-pr': '🐘 **Biggest PR merged**: [{repo}#{number}]({url}) “{title}” by @{author} (+{additions}/−{deletions}).',
    'highlight.fastest-review': '⚡ **Fastest first review**: @{reviewer} reviewed [{repo}#{number}]({url}) in {duration}.',
    'highlight.first-time-contributors': '🎉 **First-time contributors**: {logins} — welcome!',
    'highlight.most-active-repo': '🔥 **Most active repo**: **{repo}** ({prsMerged} PRs merged, {commits} commits).',
    'highlight.entry': '@{login} ({count})',

    // Merged-PR detail
    'section.mergedPrs': 'Merged PRs by repository',
    'mergedPrs.summary': '📦 View all {total} merged PRs (detail per repository)',
    'mergedPrs.item': '[{repo}#{number}]({url}) “{title}” — @{author} (+{additions}/−{deletions}, {date})',
    'mergedPrs.more': '…and {count} more',

    // Narrative fallbacks
    'narrative.skipped-no-key': '_No LLM key configured — this report is metrics-only. Add anthropic-api-key or openai-api-key for a narrative summary._',
    'narrative.skipped-dry-run': '_Dry run — LLM narrative skipped._',
    'narrative.skipped-disabled': '_LLM narrative disabled (llm-provider: none)._',
    'narrative.failed': '_The LLM call failed; showing metrics only. See the run log for details._',

    // Appendix
    'appendix.window': 'Window: {startDate} → {endDate} ({timezone}) — previous complete {period}.',
    'appendix.repos': 'Repos scanned: {scanned} (after include/exclude filters).',
    'appendix.method':
      'Numbers are computed deterministically from the GitHub API (Search + GraphQL); the LLM writes narrative only and never computes figures. Review counts cover the first 50 reviews per PR. Commits are counted on each repo’s work branch (develop/development/staging, configurable) falling back to its default branch. Person-level commit counts are not attributed in v1.',
    'appendix.llmUsage': 'LLM: {provider} {model} — {inputTokens} in / {outputTokens} out tokens{cost}.',
    'appendix.llmCost': ' (~${cost} estimated)',
    'appendix.warnings': 'Collection warnings:',
    'appendix.generatedBy': 'Generated by OmbuPulse.',

    // Period words + labels
    'periodWord.daily': 'day',
    'periodWord.weekly': 'week',
    'periodWord.biweekly': 'fortnight',
    'periodWord.monthly': 'month',
    'periodWord.custom': 'custom range',
    'period.weekly': 'Week of {start} – {end}',
    'period.biweekly': 'Weeks of {start} – {end}',
    'period.monthly': '{month}',
    'period.daily': '{start}',
    'period.custom': '{start} – {end}',

    // Durations
    'duration.minutes': '{n} min',
    'duration.hours': '{n} h',
    'duration.days': '{n} days',

    // Email/Slack chrome
    'slack.headline': '{org} — {periodLabel}',
    'slack.viewFull': 'View full report',
    'slack.noActivity': 'No tracked activity this period.',
    'email.viewRun': 'View the workflow run',
    'report.noActivity': 'No tracked activity in this window.'
  },
  es: {
    'section.executiveSummary': 'Resumen Ejecutivo',
    'section.keyNumbers': 'Números Clave',
    'section.highlights': 'Destacados',
    'section.repoActivity': 'Actividad por Repositorio',
    'section.contributors': 'Contribuidores',
    'section.appendix': 'Apéndice — metodología y salvedades',

    'metric.prsOpened': 'PRs abiertos',
    'metric.prsMerged': 'PRs mergeados',
    'metric.mergedToProduction': 'Mergeados a producción',
    'metric.mergedToStaging': 'Mergeados a staging',
    'metric.openPrTotal': 'PRs abiertos actualmente',
    'metric.issuesOpened': 'Issues abiertos',
    'metric.issuesClosed': 'Issues cerrados',
    'metric.commits': 'Commits (ramas de trabajo)',
    'metric.reviewsSubmitted': 'Reviews realizadas',
    'metric.linesChanged': 'Líneas modificadas (PRs mergeados)',
    'metric.medianTimeToMerge': 'Mediana de tiempo a merge',
    'metric.activeContributors': 'Contribuidores activos',
    'metric.activeRepos': 'Repos activos',

    'table.repo': 'Repositorio',
    'table.person': 'Contribuidor',
    'table.prsOpened': 'PRs abiertos',
    'table.prsMerged': 'PRs mergeados',
    'table.openPrs': 'PRs abiertos',
    'table.issues': 'Issues (abiertos/cerrados)',
    'table.issuesOpened': 'Issues abiertos',
    'table.commits': 'Commits',
    'table.openPrsNow': 'Abiertos hoy',
    'table.linesChanged': 'Δ líneas',
    'table.reviews': 'Reviews',
    'table.merges': 'Merges',
    'table.longTail': '…y {count} repos más ({prsMerged} PRs mergeados, {commits} commits)',

    'highlight.oldest-open-pr': '🕰️ **PR abierto más antiguo**: [{repo}#{number}]({url}) “{title}” de @{author} — abierto hace {ageDays} días.',
    'highlight.top-merger': '🚢 **Quien más mergea**: {entries}.',
    'highlight.top-reviewer': '🔍 **Top reviewer**: {entries}.',
    'highlight.stale-prs': '🧊 **PRs esperando primera review** ({totalStale} en total ≥{thresholdDays}d):',
    'highlight.stale-prs.item': '[{repo}#{number}]({url}) “{title}” de @{author} — {ageDays} días',
    'highlight.biggest-pr': '🐘 **PR más grande mergeado**: [{repo}#{number}]({url}) “{title}” de @{author} (+{additions}/−{deletions}).',
    'highlight.fastest-review': '⚡ **Primera review más rápida**: @{reviewer} revisó [{repo}#{number}]({url}) en {duration}.',
    'highlight.first-time-contributors': '🎉 **Nuevos contribuidores**: {logins} — ¡bienvenidos!',
    'highlight.most-active-repo': '🔥 **Repo más activo**: **{repo}** ({prsMerged} PRs mergeados, {commits} commits).',
    'highlight.entry': '@{login} ({count})',

    'section.mergedPrs': 'PRs mergeados por repositorio',
    'mergedPrs.summary': '📦 Ver los {total} PRs mergeados (detalle por repositorio)',
    'mergedPrs.item': '[{repo}#{number}]({url}) “{title}” — @{author} → {base} (+{additions}/−{deletions}, {date})',
    'mergedPrs.more': '…y {count} más',

    'narrative.skipped-no-key': '_Sin API key de LLM — este reporte es solo de métricas. Agregá anthropic-api-key u openai-api-key para el resumen narrativo._',
    'narrative.skipped-dry-run': '_Dry run — se omitió la narrativa del LLM._',
    'narrative.skipped-disabled': '_Narrativa LLM deshabilitada (llm-provider: none)._',
    'narrative.failed': '_Falló la llamada al LLM; se muestran solo métricas. Ver el log del run para más detalle._',

    'appendix.window': 'Ventana: {startDate} → {endDate} ({timezone}) — período completo anterior: {period}.',
    'appendix.repos': 'Repos analizados: {scanned} (después de filtros include/exclude).',
    'appendix.method':
      'Los números se calculan de forma determinística desde la API de GitHub (Search + GraphQL); el LLM solo escribe narrativa y nunca calcula cifras. Los conteos de reviews cubren las primeras 50 por PR. Los commits se cuentan sobre la rama de trabajo de cada repo (develop/development/staging, configurable) con fallback a su rama default. Los commits por persona no se atribuyen en v1.',
    'appendix.llmUsage': 'LLM: {provider} {model} — {inputTokens} tokens de entrada / {outputTokens} de salida{cost}.',
    'appendix.llmCost': ' (~${cost} estimado)',
    'appendix.warnings': 'Advertencias de recolección:',
    'appendix.generatedBy': 'Generado por OmbuPulse.',

    'periodWord.daily': 'día',
    'periodWord.weekly': 'semana',
    'periodWord.biweekly': 'quincena',
    'periodWord.monthly': 'mes',
    'periodWord.custom': 'rango personalizado',
    'period.weekly': 'Semana del {start} al {end}',
    'period.biweekly': 'Semanas del {start} al {end}',
    'period.monthly': '{month}',
    'period.daily': '{start}',
    'period.custom': '{start} – {end}',

    'duration.minutes': '{n} min',
    'duration.hours': '{n} h',
    'duration.days': '{n} días',

    'slack.headline': '{org} — {periodLabel}',
    'slack.viewFull': 'Ver reporte completo',
    'slack.noActivity': 'Sin actividad registrada en este período.',
    'email.viewRun': 'Ver el workflow run',
    'report.noActivity': 'Sin actividad registrada en esta ventana.'
  }
} as const;

export type StringKey = keyof (typeof STRINGS)['en'];

export function t(lang: Language, key: StringKey, vars: Record<string, string | number> = {}): string {
  const template: string = STRINGS[lang][key] ?? STRINGS.en[key];
  // Single pass so placeholder-looking text inside earlier values (e.g. a PR
  // title containing "{url}") is never re-expanded by later vars.
  return template.replace(/\{([\w-]+)\}/g, (match, name: string) =>
    name in vars ? String(vars[name]) : match
  );
}

const LOCALE: Record<Language, string> = { en: 'en-US', es: 'es-ES' };

/** "Jun 29" / "29 jun" style short date in the report language. */
export function shortDate(ymd: string, lang: Language): string {
  const [y, m, d] = ymd.split('-').map(Number);
  const date = new Date(Date.UTC(y!, m! - 1, d!));
  return new Intl.DateTimeFormat(LOCALE[lang], { month: 'short', day: 'numeric', timeZone: 'UTC' }).format(date);
}

export function monthName(ymd: string, lang: Language): string {
  const [y, m] = ymd.split('-').map(Number);
  const date = new Date(Date.UTC(y!, m! - 1, 1));
  const formatted = new Intl.DateTimeFormat(LOCALE[lang], { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(
    date
  );
  return formatted.charAt(0).toUpperCase() + formatted.slice(1);
}

/** Human duration from hours, in the report language. */
export function humanDuration(hours: number, lang: Language): string {
  if (hours < 1) return t(lang, 'duration.minutes', { n: Math.max(1, Math.round(hours * 60)) });
  if (hours < 48) return t(lang, 'duration.hours', { n: Math.round(hours * 10) / 10 });
  return t(lang, 'duration.days', { n: Math.round((hours / 24) * 10) / 10 });
}

export function periodLabel(
  period: string,
  startDate: string,
  endDate: string,
  lang: Language,
  year?: number
): string {
  const start = shortDate(startDate, lang);
  const end = shortDate(endDate, lang);
  const suffix = year ? `, ${year}` : '';
  switch (period) {
    case 'weekly':
      return t(lang, 'period.weekly', { start, end }) + suffix;
    case 'biweekly':
      return t(lang, 'period.biweekly', { start, end }) + suffix;
    case 'monthly':
      return t(lang, 'period.monthly', { month: monthName(startDate, lang) });
    case 'daily':
      return t(lang, 'period.daily', { start }) + suffix;
    default:
      return t(lang, 'period.custom', { start: startDate, end: endDate });
  }
}
